name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v1
      with:
        azure-cli-version: 'latest'

    - name: Log in to Azure using Service Principal
      uses: azure/login@v1
      with:
        client-id: ${{ 687eb466-c9b9-430a-bb32-8bfb0bc8f01b }}
        client-secret: ${{ 2b0f6a4c-cfd8-47f3-9922-4b7c87525224 }}
        tenant-id: ${{ d455b95d-f881-4e14-839c-4012b4b903c2 }}
        subscription-id: ${{ 3400ecc4-3a9a-43dc-a43d-adaf70beb9a7 }}

    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ firstcontainerappacracr123.azurecr.io }}.azurecr.io
        username: ${{ firstcontainerappacracr123 }}
        password: ${{ g+458osvfnWNp6FAMv36hDt8d0dI7/z4cFuE9YOiFj+ACRBhBh6v }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/my-app:latest .

    - name: Push Docker image to ACR
      run: |
        docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/my-app:latest

    - name: Set up Kubernetes kubectl
      uses: azure/setup-kubectl@v1

    - name: Deploy to AKS
      run: |
        kubectl apply -f deployment.yaml

    - name: Verify deployment
      run: |
        kubectl get pods
